/*CREATE PROCEDURE SP_PROCEDIMIENTO1
AS
	PRINT('HOLA MUNDO');

EXECUTE SP_PROCEDIMIENTO2;

CREATE PROCEDURE SP_PROCEDIMIENTO2
AS
	SELECT * FROM ALUMNO;

	*/
/*
DROP PROCEDURE SP_PROCEDIMIENTO3;

CREATE PROCEDURE SP_PROCEDIMIENTO3
@ALUMNO VARCHAR(100),
@NOTA INT
AS
DECLARE @TEMP INT
	SELECT @TEMP = NOTAID FROM NOTA WHERE NOTAID=10
	UPDATE NOTA SET NOTA = @NOTA WHERE ALUMNOID = @ALUMNO
	UPDATE NOTA SET NOTA = 100 WHERE NOTAID = @TEMP; 

EXECUTE SP_PROCEDIMIENTO3 '1-100-100',95;

SELECT * FROM NOTA


CREATE TRIGGER TG_ALUMNO
ON ALUMNO FOR INSERT
AS
DECLARE @ID VARCHAR(100)
DECLARE @NOMBRE VARCHAR(100)

SELECT @NOMBRE = NOMBRE FROM ALUMNO WHERE NOMBRE = INSERTED.NOMBRE; 




SELECT * FROM ALUMNO
*/