/*select top(100) [brandid],[name] from [demodb].[dbo].[brand]
go*/
/*
select top(100) [BEERid],[name],[BRANDID] from [demodb].[dbo].[BEER]
go
*/

/*
INSERT INTO BEER(NAME,BRANDID) VALUES('Gallo',1)
INSERT INTO BEER(NAME,BRANDID) VALUES('Dorada',1)
INSERT INTO BEER(NAME,BRANDID) VALUES('Brava',2)
INSERT INTO BEER(NAME,BRANDID) VALUES('Heineken',3)
go*/

/*
INSERT INTO BRAND(NAME) VALUES('Marca X')
INSERT INTO BRAND(NAME) VALUES('Y Marca')
INSERT INTO BRAND(NAME) VALUES('Perro')
INSERT INTO BRAND(NAME) VALUES('MGTOSDF')
go

INSERT INTO BEER(NAME,BRANDID) VALUES('Gallo',1)
INSERT INTO BEER(NAME,BRANDID) VALUES('Dorada',1)
INSERT INTO BEER(NAME,BRANDID) VALUES('Brava',2)
INSERT INTO BEER(NAME,BRANDID) VALUES('Heineken',3)
go
*/