CREATE DATABASE TESTDB
GO

USE TESTDB
GO

CREATE TABLE PRODUCTTYPE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(75) NOT NULL,
	DESCRIPTION VARCHAR(100)
)
GO

INSERT INTO PRODUCTTYPE(NAME,DESCRIPTION) VALUES('MANZANA','DESCRPICION MANZANAS')
GO